[project]
name = "steam-platform-stats"
version = "0.2.3"
description = "A tool to display user's Steam games statistics by platform"
license = "MIT"
authors = [{ name = "Ivan Batrakov", email = "blackfan321@gmail.com" }]
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "argcomplete>=3.7.0",
    "prettytable>=3.18.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "xdg-base-dirs>=6.0.2",
]

[project.scripts]
steam-platform-stats = "steam_platform_stats.main:main"

[build-system]
requires = ["uv-build>=0.10,<0.12"]
build-backend = "uv_build"
